using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

// ReSharper disable RedundantNameQualifier

namespace Sawczyn.EFDesigner.EFModel.EditingOnly
{
   // ReSharper disable once UnusedMember.Global
   public partial class GeneratedTextTransformation
   {
      #region Template

      // EFDesigner v4.2.8.1
      // Copyright (c) 2017-2023 Michael Sawczyn
      // https://github.com/msawczyn/EFDesigner

      /// <summary>
      /// Generates a Markdown model manifest file that provides a human-and-AI-readable
      /// representation of the entire EF model, including entities, properties, enums,
      /// relationships, inheritance hierarchies, and diagram structure.
      /// </summary>
      public class EFModelManifestGenerator
      {
         private readonly ModelRoot modelRoot;

         /// <summary>
         /// Initializes a new instance of the EFModelManifestGenerator class.
         /// </summary>
         /// <param name="modelRoot">The model root containing the entity information.</param>
         public EFModelManifestGenerator(ModelRoot modelRoot)
         {
            this.modelRoot = modelRoot ?? throw new ArgumentNullException(nameof(modelRoot));
         }

         /// <summary>
         /// Generates the full Markdown content of the model manifest.
         /// </summary>
         /// <returns>The Markdown string.</returns>
         public string GenerateManifestContent()
         {
            StringBuilder sb = new StringBuilder();

            WriteHeader(sb);
            WriteModelOverview(sb);
            WriteEnumDefinitions(sb);
            WriteEntityRegistry(sb);
            WriteInheritanceHierarchy(sb);
            WriteDiagramStructure(sb);

            return sb.ToString();
         }

         private void WriteHeader(StringBuilder sb)
         {
            sb.AppendLine("<!-- Auto-generated model manifest. Do not edit manually. -->");
            sb.AppendLine($"<!-- Generated by Entity Framework Visual Editor v{modelRoot.DSLVersion} -->");
            sb.AppendLine($"<!-- Source: {modelRoot.EntityContainerName}.efmodel -->");
            sb.AppendLine();
         }

         private void WriteModelOverview(StringBuilder sb)
         {
            sb.AppendLine($"# Model Manifest: {modelRoot.EntityContainerName}");
            sb.AppendLine();

            if (!string.IsNullOrWhiteSpace(modelRoot.Summary))
            {
               sb.AppendLine($"> {EscapeMarkdown(modelRoot.Summary)}");
               sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(modelRoot.Description))
            {
               sb.AppendLine(EscapeMarkdown(modelRoot.Description));
               sb.AppendLine();
            }

            sb.AppendLine("## Model Configuration");
            sb.AppendLine();
            sb.AppendLine("| Setting | Value |");
            sb.AppendLine("|---------|-------|");
            sb.AppendLine($"| Namespace | `{modelRoot.Namespace}` |");
            sb.AppendLine($"| Entity Framework | {FormatEFVersion()} |");
            sb.AppendLine($"| Inheritance Strategy (Default) | {FormatCodeStrategy(modelRoot.InheritanceStrategyDefault)} |");
            sb.AppendLine($"| Database Schema | {(string.IsNullOrWhiteSpace(modelRoot.DatabaseSchema) ? "(default)" : $"`{modelRoot.DatabaseSchema}`")} |");
            sb.AppendLine($"| Entity Count | {modelRoot.Classes.Count()} |");
            sb.AppendLine($"| Enum Count | {modelRoot.Enums.Count()} |");
            sb.AppendLine();
         }

         private void WriteEnumDefinitions(StringBuilder sb)
         {
            IOrderedEnumerable<ModelEnum> enums = modelRoot.Enums.OrderBy(e => e.Name);

            if (!enums.Any())
               return;

            sb.AppendLine("## Enumerations");
            sb.AppendLine();

            foreach (ModelEnum modelEnum in enums)
            {
               sb.AppendLine($"### Enum: {modelEnum.Name}");
               sb.AppendLine();

               if (!string.IsNullOrWhiteSpace(modelEnum.Summary))
               {
                  sb.AppendLine($"> {EscapeMarkdown(modelEnum.Summary)}");
                  sb.AppendLine();
               }

               sb.AppendLine($"- **Namespace**: `{(string.IsNullOrWhiteSpace(modelEnum.Namespace) ? modelRoot.Namespace : modelEnum.Namespace)}`");
               sb.AppendLine($"- **Underlying Type**: `{modelEnum.ValueType}`");

               if (modelEnum.IsFlags)
                  sb.AppendLine("- **Flags**: yes");

               sb.AppendLine();

               sb.AppendLine("| Name | Value | Display Text | Description |");
               sb.AppendLine("|------|-------|-------------|-------------|");

               foreach (ModelEnumValue enumValue in modelEnum.Values)
               {
                  string value = string.IsNullOrWhiteSpace(enumValue.Value) ? "-" : enumValue.Value;
                  string displayText = string.IsNullOrWhiteSpace(enumValue.DisplayText) ? "-" : EscapeMarkdown(enumValue.DisplayText);
                  string description = string.IsNullOrWhiteSpace(enumValue.Description) ? "-" : EscapeMarkdown(enumValue.Description);
                  sb.AppendLine($"| {enumValue.Name} | {value} | {displayText} | {description} |");
               }

               sb.AppendLine();
            }
         }

         private void WriteEntityRegistry(StringBuilder sb)
         {
            IOrderedEnumerable<ModelClass> classes = modelRoot.Classes.OrderBy(c => c.Name);

            if (!classes.Any())
               return;

            sb.AppendLine("## Entities");
            sb.AppendLine();

            foreach (ModelClass modelClass in classes)
            {
               WriteEntity(sb, modelClass);
            }
         }

         private void WriteEntity(StringBuilder sb, ModelClass modelClass)
         {
            sb.AppendLine($"### Entity: {modelClass.Name}");
            sb.AppendLine();

            // Summary line
            List<string> tags = new List<string>();

            if (!string.IsNullOrWhiteSpace(modelClass.TableName))
               tags.Add($"Table: {modelClass.TableName}");
            else if (modelClass.IsPersistent)
               tags.Add($"Table: {modelClass.Name}");

            if (modelClass.Superclass != null)
               tags.Add($"Extends: {modelClass.Superclass.Name}");

            if (!string.IsNullOrWhiteSpace(modelClass.CustomInterfaces))
               tags.Add($"Implements: {modelClass.CustomInterfaces}");

            if (modelClass.IsAbstract)
               tags.Add("Abstract");

            if (!modelClass.IsPersistent)
               tags.Add("Transient");

            if (modelClass.IsDependentType)
               tags.Add("Owned Type");

            if (tags.Any())
            {
               sb.AppendLine(string.Join(" | ", tags));
               sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(modelClass.Summary))
            {
               sb.AppendLine($"> {EscapeMarkdown(modelClass.Summary)}");
               sb.AppendLine();
            }

            if (!string.IsNullOrWhiteSpace(modelClass.Description))
            {
               sb.AppendLine(EscapeMarkdown(modelClass.Description));
               sb.AppendLine();
            }

            // Additional metadata
            List<string> metadata = new List<string>();

            if (!string.IsNullOrWhiteSpace(modelClass.Namespace) && modelClass.Namespace != modelRoot.Namespace)
               metadata.Add($"- **Namespace**: `{modelClass.Namespace}`");

            if (!string.IsNullOrWhiteSpace(modelClass.DatabaseSchema))
               metadata.Add($"- **Schema**: `{modelClass.DatabaseSchema}`");

            if (!string.IsNullOrWhiteSpace(modelClass.DbSetName))
               metadata.Add($"- **DbSet**: `{modelClass.DbSetName}`");

            if (!string.IsNullOrWhiteSpace(modelClass.CustomAttributes))
               metadata.Add($"- **Custom Attributes**: `{modelClass.CustomAttributes}`");

            if (metadata.Any())
            {
               foreach (string line in metadata)
                  sb.AppendLine(line);

               sb.AppendLine();
            }

            // Properties table
            WriteEntityProperties(sb, modelClass);

            // Relationships
            WriteEntityRelationships(sb, modelClass);
         }

         private void WriteEntityProperties(StringBuilder sb, ModelClass modelClass)
         {
            IEnumerable<ModelAttribute> attributes = modelClass.Attributes;

            if (!attributes.Any())
               return;

            sb.AppendLine("#### Properties");
            sb.AppendLine();
            sb.AppendLine("| Property | Type | Required | Identity | MaxLength | Default | Concurrency | Description |");
            sb.AppendLine("|----------|------|----------|----------|-----------|---------|-------------|-------------|");

            foreach (ModelAttribute attr in attributes)
            {
               string required = attr.Required ? "yes" : "no";
               string identity = attr.IsIdentity ? "yes" : "-";
               string maxLength = attr.MaxLength > 0 ? attr.MaxLength.ToString() : "-";

               string defaultValue = !string.IsNullOrWhiteSpace(attr.InitialValue) ? EscapeMarkdown(attr.InitialValue) : "-";
               string concurrency = attr.IsConcurrencyToken ? "yes" : "-";
               string description = !string.IsNullOrWhiteSpace(attr.Summary) ? EscapeMarkdown(attr.Summary) : "-";

               string persistent = attr.Persistent ? "" : " *(transient)*";
               string typeName = attr.Type + persistent;

               sb.AppendLine($"| {attr.Name} | `{typeName}` | {required} | {identity} | {maxLength} | {defaultValue} | {concurrency} | {description} |");
            }

            sb.AppendLine();
         }

         private void WriteEntityRelationships(StringBuilder sb, ModelClass modelClass)
         {
            List<string> relationshipLines = new List<string>();

            // Associations where this entity is the source (outgoing)
            foreach (Association association in Association.GetLinksToTargets(modelClass))
            {
               string direction = association is BidirectionalAssociation ? "↔" : "→";
               string cardinality = FormatCardinality(association.SourceMultiplicity, association.TargetMultiplicity);
               string targetName = association.Target.Name;
               string deleteAction = FormatDeleteAction(association.TargetDeleteAction);

               string navProperty = association.TargetPropertyName;
               string fkInfo = !string.IsNullOrWhiteSpace(association.FKPropertyName) ? $", FK: {association.FKPropertyName}" : "";

               BidirectionalAssociation biAssoc = association as BidirectionalAssociation;
               string sourceNav = biAssoc != null ? $", inverse nav: {biAssoc.SourcePropertyName}" : "";

               relationshipLines.Add($"- {direction} **{targetName}** ({cardinality}{fkInfo}, {deleteAction}, nav: `{navProperty}`{sourceNav})");
            }

            // Associations where this entity is the target (incoming unidirectional only - bidirectional already shown)
            foreach (Association association in Association.GetLinksToSources(modelClass))
            {
               // Only show incoming unidirectional associations (bidirectional already covered above via targets)
               if (association is BidirectionalAssociation)
                  continue;

               string cardinality = FormatCardinality(association.SourceMultiplicity, association.TargetMultiplicity);
               string sourceName = association.Source.Name;
               string deleteAction = FormatDeleteAction(association.SourceDeleteAction);

               relationshipLines.Add($"- ← **{sourceName}** ({cardinality}, {deleteAction}, target of unidirectional)");
            }

            // Inheritance
            if (modelClass.Superclass != null)
               relationshipLines.Add($"- ⬆ inherits from **{modelClass.Superclass.Name}**");

            if (modelClass.Subclasses.Any())
            {
               string subclassNames = string.Join(", ", modelClass.Subclasses.OrderBy(s => s.Name).Select(s => $"**{s.Name}**"));
               relationshipLines.Add($"- ⬇ base class of {subclassNames}");
            }

            if (relationshipLines.Any())
            {
               sb.AppendLine("#### Relationships");
               sb.AppendLine();

               foreach (string line in relationshipLines)
                  sb.AppendLine(line);

               sb.AppendLine();
            }
         }

         private void WriteInheritanceHierarchy(StringBuilder sb)
         {
            // Find root classes (classes with no superclass that have subclasses)
            List<ModelClass> rootClasses = modelRoot.Classes
                                                    .Where(c => c.Superclass == null && c.Subclasses.Any())
                                                    .OrderBy(c => c.Name)
                                                    .ToList();

            if (!rootClasses.Any())
               return;

            sb.AppendLine("## Inheritance Hierarchies");
            sb.AppendLine();

            foreach (ModelClass rootClass in rootClasses)
            {
               string strategy = FormatCodeStrategy(rootClass.InheritanceStrategy);
               sb.AppendLine($"**Strategy**: {strategy}");
               sb.AppendLine();
               sb.AppendLine("```");
               WriteInheritanceTree(sb, rootClass, "", true);
               sb.AppendLine("```");
               sb.AppendLine();
            }
         }

         private void WriteInheritanceTree(StringBuilder sb, ModelClass modelClass, string prefix, bool isLast)
         {
            string connector = string.IsNullOrEmpty(prefix) ? "" : (isLast ? "└── " : "├── ");
            string abstractMarker = modelClass.IsAbstract ? " *(abstract)*" : "";
            sb.AppendLine($"{prefix}{connector}{modelClass.Name}{abstractMarker}");

            List<ModelClass> subclasses = modelClass.Subclasses.OrderBy(s => s.Name).ToList();
            string childPrefix = string.IsNullOrEmpty(prefix) ? "" : prefix + (isLast ? "    " : "│   ");

            for (int i = 0; i < subclasses.Count; i++)
            {
               WriteInheritanceTree(sb, subclasses[i], childPrefix, i == subclasses.Count - 1);
            }
         }

         private void WriteDiagramStructure(StringBuilder sb)
         {
            if (!modelRoot.Diagrams.Any())
               return;

            sb.AppendLine("## Diagrams");
            sb.AppendLine();

            foreach (ModelDiagramData diagram in modelRoot.Diagrams.OrderBy(d => d.Name))
            {
               sb.AppendLine($"### {diagram.Name}");
               sb.AppendLine();

               // Get the EFModelDiagram to find which entities are on it
               EFModelDiagram efDiagram = diagram.GetDiagram();

               if (efDiagram != null)
               {
                  // Collect entity names from shapes on this diagram
                  List<string> entityNames = new List<string>();
                  List<string> enumNames = new List<string>();
                  List<string> commentTexts = new List<string>();

                  foreach (Microsoft.VisualStudio.Modeling.Diagrams.ShapeElement shape in efDiagram.NestedChildShapes)
                  {
                     if (shape is ClassShape classShape && classShape.ModelElement is ModelClass modelClass)
                        entityNames.Add(modelClass.Name);
                     else if (shape is EnumShape enumShape && enumShape.ModelElement is ModelEnum modelEnum)
                        enumNames.Add(modelEnum.Name);
                     else if (shape is CommentBoxShape commentShape && commentShape.ModelElement is Comment comment
                              && !string.IsNullOrWhiteSpace(comment.Text))
                        commentTexts.Add(comment.Text);
                  }

                  if (commentTexts.Any())
                  {
                     foreach (string commentText in commentTexts)
                     {
                        sb.AppendLine($"> {EscapeMarkdown(commentText)}");
                        sb.AppendLine();
                     }
                  }

                  if (entityNames.Any())
                  {
                     sb.AppendLine($"**Entities**: {string.Join(", ", entityNames.OrderBy(n => n))}");
                     sb.AppendLine();
                  }

                  if (enumNames.Any())
                  {
                     sb.AppendLine($"**Enums**: {string.Join(", ", enumNames.OrderBy(n => n))}");
                     sb.AppendLine();
                  }
               }
               else
               {
                  sb.AppendLine("*(Diagram not loaded)*");
                  sb.AppendLine();
               }
            }
         }

         // Diagram shape classes are from the DSL, not always directly available in the T4 context.
         // We'll use a runtime-safe approach that works even when diagram shapes aren't loaded.

         private static string FormatCardinality(Multiplicity source, Multiplicity target)
         {
            return $"{FormatMultiplicity(source)}:{FormatMultiplicity(target)}";
         }

         private static string FormatMultiplicity(Multiplicity multiplicity)
         {
            switch (multiplicity)
            {
               case Multiplicity.One:
                  return "1";

               case Multiplicity.ZeroOne:
                  return "0..1";

               case Multiplicity.ZeroMany:
                  return "*";

               default:
                  return "?";
            }
         }

         private static string FormatDeleteAction(DeleteAction action)
         {
            switch (action)
            {
               case DeleteAction.Cascade:
                  return "cascade";

               case DeleteAction.None:
                  return "no action";

               case DeleteAction.Default:
                  return "default";

               default:
                  return action.ToString();
            }
         }

         private string FormatEFVersion()
         {
            if (modelRoot.EntityFrameworkVersion == EFVersion.EF6)
               return "Entity Framework 6";

            return $"EF Core {modelRoot.EntityFrameworkPackageVersion}";
         }

         private static string FormatCodeStrategy(CodeStrategy strategy)
         {
            switch (strategy)
            {
               case CodeStrategy.TablePerHierarchy:
                  return "TPH (Table Per Hierarchy)";

               case CodeStrategy.TablePerType:
                  return "TPT (Table Per Type)";

               case CodeStrategy.TablePerConcreteType:
                  return "TPC (Table Per Concrete Type)";

               default:
                  return strategy.ToString();
            }
         }

         private static string EscapeMarkdown(string text)
         {
            if (string.IsNullOrEmpty(text))
               return text;

            // Replace pipe characters that would break table formatting
            return text.Replace("|", "\\|").Replace("\r\n", " ").Replace("\n", " ").Replace("\r", " ");
         }
      }

      #endregion Template
   }
}
